version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - MYSQL_DATABASE=myDb
      - MYSQL_ROOT_HOST=%
